---
# 重启一套应用系统的典型场景
# 停止前端服务
  - hosts: loadbalancer
    become: true
    tasks:
      - name: Stop loadbalancer
        service: 
          name: nginx
          state: stopped  
  - hosts: webserver
    become: true
    tasks:
      - name: Stop Web server
        service: 
          name: apache2
          state: stopped

# 重启后台数据库        
  - hosts: database
    become: true
    tasks:
      - name: Restart backend database
        service: 
          name: mysql
          state: restarted

# 启动前端服务
  - hosts: loadbalancer
    become: true
    tasks:
      - name: start loadbalancer again
        service: 
          name: nginx
          state: started
  
  - hosts: webserver
    become: true
    tasks:
      - name: Start Web server
        service: 
          name: apache2
          state: started