# 替换所有软仓库 repo 
# 这里用的是 MacOS host 上的 Nexus 服务器地址
# CentOS 7 的 3 个 repo + Elastic Stack 7x
---
- name: Replace mirror repo 
  hosts: es
  become: true
  tasks:
  - name: Remove all old repos
    shell: "rm -rf /etc/yum.repos.d/*"
  - name: Add centos repo
    yum_repository:
      name: baseos
      description: Tsinghua Tuna centos $releasever baseos
      file: os_repos
      baseurl: http://192.168.100.30/repository/tuna-centos-proxy/$releasever/os/$basearch
      gpgcheck: no
  - name: Add updates repo
    yum_repository:
      name: updates
      description: Tsinghua Tuna centos $releasever updates
      file: os_repos
      baseurl: http://192.168.100.30/repository/tuna-centos-proxy/$releasever/updates/$basearch
      gpgcheck: no
  - name: Add elastic stack 7x repo
    yum_repository:
      name: es7x
      description: Tsinghua Tuna elastic stack 7x
      file: os_repos
      baseurl: http://192.168.100.30/repository/proxy-es7/
      gpgcheck: no
    notify: yum-clean-metadata
  # Handler showing how to clean yum metadata cache
  handlers:
    - name: yum-clean-metadata
      command: yum clean metadata
      args:
        warn: no