---
- hosts: loadbalancer
  become: true
  tasks:
    - name: install nginx
      apt: name=nginx state=present update_cache=yes

    - name: ensuser nginx service started
      service: name=nginx state=started enabled=yes